### PR TITLE
(Partially) Restored OST + Fixed Sprites

### PR DESCRIPTION
**Pull request by Heapons**

### CODE REVIEW

**Comment by hikari-no-yume** [comment]
No documentation of sources?

**Comment by Heapons** [comment]
Ah, I apologies. I restored the soundtrack thanks to Elkondo's project files, and I've tweaked the sprites on my own.

**Comment by wareya** [comment]
Er... Why doesn't the menu background have eyes anymore?

**Comment by Heapons** [comment]
I wanted to be consistent with the in-game sprites. Sorry if that makes it weird lol.

**Comment by wareya** [comment]
Yeah it makes it kind of weird. It's not at all unusual or inconsistent for art styles to selectively decide when to draw or not draw eyes in low-detail images. It happens all the time in manga for example. This is just another example of that same thing.

**Comment by Heapons** [comment]
Do you want me to put the eyes back then?

**Comment by wareya** [comment]
I would like it, but it's subject to what medo thinks.

**Comment by Heapons** [comment]
Here you go. Even though I kept the eyeless ones as well just in case.

**Comment by wareya** [comment]
I think going back to the original mask design for the infiltrator would be a good idea even if it's inconsistent with other depictions of it; anything else I try looks weird with the single-pixel eyes, and two-pixel eyes are too strong. Also, I'm so used to seeing this particular overweight with eyes that having it without eyes just looks weird.

**Comment by Heapons** [comment]
<s>Mixels</s> Inconsistency was bothering me a lot, but being used to the old one might be a fair point.

**Comment by wareya** [comment]
The original of this menu background doesn't have any mixels though?

**Comment by Heapons** [comment]
Oh nevermind, I just checked. Sorry.

**Pull request closed without merging**
